kind: PersistentVolume
apiVersion: v1
metadata:
  name: es-pv-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/es/es2"
