FROM jenkins/jenkins:jdk11

USER root
COPY jdk-13.0.2 /opt/jdk-13.0.2
COPY apache-maven-3.6.3 /opt/apache-maven-3.6.3
COPY *.deb /tmp/

RUN ln -s /opt/apache-maven-3.6.3/bin/mvn /usr/bin/mvn #I could also simply set MVN_HOME in the pipeline
RUN apt update && apt install -y libseccomp2 iptables libdevmapper1.02.1 acl #needed for docker, acl fr setfacl
RUN dpkg -i /tmp/*.deb

RUN usermod -aG docker jenkins
RUN touch /var/run/docker.sock
RUN setfacl -m user:jenkins:rw /var/run/docker.sock

#Doesn't work but this is what's missing and causes the https call by default
#RUN echo "DOCKER_OPTS=--insecure-registry=10.244.0.1:5000" >> /etc/default/docker

USER jenkins
