{
 "title": "Business metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "movies_manager_instance",
    "label": "instance movies-manager",
    "query": "label_values(system_cpu_usage{application=\"movies-manager\"}, instance)"
   },
   {
    "name": "cache_movies_instance",
    "label": "instance cache-movies",
    "query": "label_values(system_cpu_usage{application=\"cache-movies-manager\"}, instance)"
   },
   {
    "name": "cache_tags_instance",
    "label": "instance cache-tags",
    "query": "label_values(system_cpu_usage{application=\"cache-tags-manager\"}, instance)"
   },
   {
    "name": "cache_ratings_instance",
    "label": "instance cache-ratings",
    "query": "label_values(jvm_memory_heap_init{application=\"cache-ratings-manager\"}, instance)"
   },
   {
    "name": "converter_gateway_instance",
    "label": "instance converter-gateway",
    "query": "label_values(python_info{service=\"converter-gateway\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Movies-manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Movies imported",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "movies_imported_total{application=\"movies-manager\", instance=\"$movies_manager_instance\"}"
    }
   ]
  },
  {
   "title": "Tags imported",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tags_imported_total{application=\"movies-manager\", instance=\"$movies_manager_instance\"}"
    }
   ]
  },
  {
   "title": "Tags added",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tags_added_total{application=\"movies-manager\", instance=\"$movies_manager_instance\"}"
    }
   ]
  },
  {
   "title": "Ratings imported",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ratings_imported_total{application=\"movies-manager\", instance=\"$movies_manager_instance\"}"
    }
   ]
  },
  {
   "title": "Ratings added",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ratings_added_total{application=\"movies-manager\", instance=\"$movies_manager_instance\"}"
    }
   ]
  },
  {
   "title": "Errors during movies import",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "movies_imported_errors_total{application=\"movies-manager\", instance=\"$movies_manager_instance\"}"
    }
   ]
  },
  {
   "title": "Errors during tags import",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tags_imported_errors_total{application=\"movies-manager\", instance=\"$movies_manager_instance\"}"
    }
   ]
  },
  {
   "title": "Errors during tags adding",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tags_added_errors_total{application=\"movies-manager\", instance=\"$movies_manager_instance\"}"
    }
   ]
  },
  {
   "title": "Errors during ratings import",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ratings_imported_errors_total{application=\"movies-manager\", instance=\"$movies_manager_instance\"}"
    }
   ]
  },
  {
   "title": "Errors during ratings adding",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ratings_added_errors_total{application=\"movies-manager\", instance=\"$movies_manager_instance\"}"
    }
   ]
  },
  { "title": "Cache of tags", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Tags searched",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tags_searched_total{application=\"cache-tags-manager\", instance=\"$cache_tags_instance\"}"
    }
   ]
  },
  {
   "title": "Tags imported",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tags_imported_total{application=\"cache-tags-manager\", instance=\"$cache_tags_instance\"}"
    }
   ]
  },
  {
   "title": "Errors during tags import",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tags_imported_errors_total{application=\"cache-tags-manager\", instance=\"$cache_tags_instance\"}"
    }
   ]
  },
  {
   "title": "Tags added",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tags_added_total{application=\"cache-tags-manager\", instance=\"$cache_tags_instance\"}"
    }
   ]
  },
  {
   "title": "Errors during tags adding",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tags_added_errors_total{application=\"cache-tags-manager\", instance=\"$cache_tags_instance\"}"
    }
   ]
  },
  { "title": "Cache of movies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Movies searched",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "movies_searched_total{application=\"cache-movies-manager\", instance=\"$cache_movies_instance\"}"
    }
   ]
  },
  {
   "title": "Movies imported",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "movies_imported_total{application=\"cache-movies-manager\", instance=\"$cache_movies_instance\"}"
    }
   ]
  },
  {
   "title": "Errors during movies import",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "movies_imported_errors_total{application=\"cache-movies-manager\", instance=\"$cache_movies_instance\"}"
    }
   ]
  },
  {
   "title": "Tags added",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tags_added_total{application=\"cache-movies-manager\", instance=\"$cache_movies_instance\"}"
    }
   ]
  },
  {
   "title": "Errors during tags adding",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tags_added_errors_total{application=\"cache-movies-manager\", instance=\"$cache_movies_instance\"}"
    }
   ]
  },
  { "title": "Cache of ratings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Ratings searched",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ratings_searched_total{application=\"cache-ratings-manager\", instance=\"$cache_ratings_instance\"}"
    }
   ]
  },
  {
   "title": "Ratings imported",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ratings_imported_total{application=\"cache-ratings-manager\", instance=\"$cache_ratings_instance\"}"
    }
   ]
  },
  {
   "title": "Errors during ratings import",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ratings_imported_errors_total{application=\"cache-ratings-manager\", instance=\"$cache_ratings_instance\"}"
    }
   ]
  },
  {
   "title": "Ratings added",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ratings_added_total{application=\"cache-ratings-manager\", instance=\"$cache_ratings_instance\"}"
    }
   ]
  },
  {
   "title": "Errors during ratings adding",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ratings_added_errors_total{application=\"cache-ratings-manager\", instance=\"$cache_ratings_instance\"}"
    }
   ]
  },
  { "title": "Converter gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Tags added",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tags_added_total{application=\"converter-gateway\", instance=\"$converter_gateway_instance\"}"
    }
   ]
  },
  {
   "title": "Errors during tags adding",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tags_added_errors_total{application=\"converter-gateway\", instance=\"$converter_gateway_instance\"}"
    }
   ]
  },
  {
   "title": "Ratings added",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ratings_added_total{application=\"converter-gateway\", instance=\"$converter_gateway_instance\"}"
    }
   ]
  },
  {
   "title": "Errors during ratings adding",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ratings_added_errors_total{application=\"converter-gateway\", instance=\"$converter_gateway_instance\"}"
    }
   ]
  }
 ]
}