{
 "title": "Public dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Movies-manager + dedicated Mongodb technical metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mongodb query operations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_op_counters_total[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Mongodb document operations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 3, "x": 4, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_mongod_metrics_document_total[$__rate_interval])",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Mongodb memory usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 7, "y": 1 },
     "yaxes": [
      { "format": "decmbytes", "label": "MB" }
     ],
     "targets": [
      {
       "expr": "mongodb_memory{type=~\"resident|virtual\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Mongodb memory usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{container=\"mongo\"}"
      }
     ]
    },
    {
     "title": "Mongodb cpu load avg 10s",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 15, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "container_cpu_load_average_10s{container=\"mongo\"}"
      }
     ]
    },
    {
     "title": "Movies-manager JVM Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"movies-manager\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{application=\"movies-manager\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{application=\"movies-manager\"})",
       "legendFormat": "max"
      },
      {
       "expr": "process_memory_rss_bytes{application=\"movies-manager\"}",
       "legendFormat": "rss"
      },
      {
       "expr": "process_memory_pss_bytes{application=\"movies-manager\"}",
       "legendFormat": "pss"
      },
      {
       "expr": "process_memory_swap_bytes{application=\"movies-manager\"}",
       "legendFormat": "swap"
      },
      {
       "expr": "process_memory_swappss_bytes{application=\"movies-manager\"}",
       "legendFormat": "swappss"
      },
      {
       "expr": "process_memory_pss_bytes{application=\"movies-manager\"} + process_memory_swap_bytes{application=\"movies-manager\"}",
       "legendFormat": "phys (pss+swap)"
      }
     ]
    },
    {
     "title": "Movies-manager cpu usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage{application=\"movies-manager\"}",
       "legendFormat": "system"
      },
      {
       "expr": "process_cpu_usage{application=\"movies-manager\"}",
       "legendFormat": "process"
      },
      {
       "expr": "avg_over_time(process_cpu_usage{application=\"movies-manager\"}[$__rate_interval])",
       "legendFormat": "process-1h"
      }
     ]
    },
    {
     "title": "Movies-manager http rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"movies-manager\"}[$__rate_interval]))",
       "legendFormat": "HTTP"
      }
     ]
    }
   ]
  },
  {
   "title": "Movies-manager business metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Movies imported",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "movies_imported_total{application=\"movies-manager\"}"
    }
   ]
  },
  {
   "title": "Tags imported",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tags_imported_total{application=\"movies-manager\"}"
    }
   ]
  },
  {
   "title": "Ratings imported",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ratings_imported_total{application=\"movies-manager\"}"
    }
   ]
  },
  {
   "title": "Tags added",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tags_added_total{application=\"movies-manager\"}"
    }
   ]
  },
  {
   "title": "Ratings added",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ratings_added_total{application=\"movies-manager\"}"
    }
   ]
  },
  {
   "title": "Errors during movies import",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "movies_imported_errors_total{application=\"movies-manager\"}"
    }
   ]
  },
  {
   "title": "Errors during tags import",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tags_imported_errors_total{application=\"movies-manager\"}"
    }
   ]
  },
  {
   "title": "Errors during ratings import",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ratings_imported_errors_total{application=\"movies-manager\"}"
    }
   ]
  },
  {
   "title": "Errors during tags adding",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tags_added_errors_total{application=\"movies-manager\"}"
    }
   ]
  },
  {
   "title": "Errors during ratings adding",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ratings_added_errors_total{application=\"movies-manager\"}"
    }
   ]
  },
  {
   "title": "Cache of tags + dedicated ElasticSearch technical metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "ElasticSearch CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percent", "label": "CPU usage" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_process_cpu_percent",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "ElasticSearch JVM memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_jvm_memory_used_bytes",
       "legendFormat": "{{name}} used: {{area}}"
      },
      {
       "expr": "elasticsearch_jvm_memory_max_bytes",
       "legendFormat": "{{name}} max: {{area}}"
      },
      {
       "expr": "elasticsearch_jvm_memory_pool_peak_used_bytes",
       "legendFormat": "{{name}} peak used pool: {{pool}}"
      }
     ]
    },
    {
     "title": "ElasticSearch total operations  rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 14, "y": 3 },
     "yaxes": [
      { "format": "short", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_indexing_index_total[$__rate_interval])",
       "legendFormat": "{{name}}: indexing"
      },
      {
       "expr": "rate(elasticsearch_indices_search_query_total[$__rate_interval])",
       "legendFormat": "{{name}}: query"
      },
      {
       "expr": "rate(elasticsearch_indices_search_fetch_total[$__rate_interval])",
       "legendFormat": "{{name}}: fetch"
      },
      {
       "expr": "rate(elasticsearch_indices_merges_total[$__rate_interval])",
       "legendFormat": "{{name}}: merges"
      },
      {
       "expr": "rate(elasticsearch_indices_refresh_total[$__rate_interval])",
       "legendFormat": "{{name}}: refresh"
      },
      {
       "expr": "rate(elasticsearch_indices_flush_total[$__rate_interval])",
       "legendFormat": "{{name}}: flush"
      },
      {
       "expr": "rate(elasticsearch_indices_get_exists_total[$__rate_interval])",
       "legendFormat": "{{name}}: get_exists"
      },
      {
       "expr": "rate(elasticsearch_indices_get_missing_total[$__rate_interval])",
       "legendFormat": "{{name}}: get_missing"
      },
      {
       "expr": "rate(elasticsearch_indices_get_total[$__rate_interval])",
       "legendFormat": "{{name}}: get"
      },
      {
       "expr": "rate(elasticsearch_indices_indexing_delete_total[$__rate_interval])",
       "legendFormat": "{{name}}: indexing_delete"
      }
     ]
    },
    {
     "title": "Cache tags JVM Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"cache-tags-manager\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{application=\"cache-tags-manager\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{application=\"cache-tags-manager\"})",
       "legendFormat": "max"
      },
      {
       "expr": "process_memory_rss_bytes{application=\"cache-tags-manager\"}",
       "legendFormat": "rss"
      },
      {
       "expr": "process_memory_pss_bytes{application=\"cache-tags-manager\"}",
       "legendFormat": "pss"
      },
      {
       "expr": "process_memory_swap_bytes{application=\"cache-tags-manager\"}",
       "legendFormat": "swap"
      },
      {
       "expr": "process_memory_swappss_bytes{application=\"cache-tags-manager\"}",
       "legendFormat": "swappss"
      },
      {
       "expr": "process_memory_pss_bytes{application=\"cache-tags-manager\"} + process_memory_swap_bytes{application=\"cache-tags-manager\"}",
       "legendFormat": "phys (pss+swap)"
      }
     ]
    },
    {
     "title": "Cache tags cpu usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage{application=\"cache-tags-manager\"}",
       "legendFormat": "system"
      },
      {
       "expr": "process_cpu_usage{application=\"cache-tags-manager\"}",
       "legendFormat": "process"
      },
      {
       "expr": "avg_over_time(process_cpu_usage{application=\"cache-tags-manager\"}[$__rate_interval])",
       "legendFormat": "process-1h"
      }
     ]
    },
    {
     "title": "Cache tags http rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"cache-tags-manager\"}[$__rate_interval]))",
       "legendFormat": "HTTP"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache of tags business metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tags searched",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tags_searched_total{application=\"cache-tags-manager\"}"
      }
     ]
    },
    {
     "title": "Tags imported",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tags_imported_total{application=\"cache-tags-manager\"}"
      }
     ]
    },
    {
     "title": "Errors during tags import",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tags_imported_errors_total{application=\"cache-tags-manager\"}"
      }
     ]
    },
    {
     "title": "Tags added",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tags_added_total{application=\"cache-tags-manager\"}"
      }
     ]
    },
    {
     "title": "Errors during tags adding",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tags_added_errors_total{application=\"cache-tags-manager\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache of movies + dedicated Redis technical metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Commands Executed / sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(redis_commands_processed_total[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Redis CPU Sys rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(redis_cpu_sys_seconds_total[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Total Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "redis_memory_used_bytes", "legendFormat": "used" },
      { "expr": "redis_memory_max_bytes", "legendFormat": "max" }
     ]
    },
    {
     "title": "Total Items per DB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 17, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      { "expr": "sum (redis_db_keys) by (db)", "legendFormat": "{{ db }} " }
     ]
    },
    {
     "title": "Cache movies JVM Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"cache-movies-manager\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{application=\"cache-movies-manager\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{application=\"cache-movies-manager\"})",
       "legendFormat": "max"
      },
      {
       "expr": "process_memory_rss_bytes{application=\"cache-movies-manager\"}",
       "legendFormat": "rss"
      },
      {
       "expr": "process_memory_pss_bytes{application=\"cache-movies-manager\"}",
       "legendFormat": "pss"
      },
      {
       "expr": "process_memory_swap_bytes{application=\"cache-movies-manager\"}",
       "legendFormat": "swap"
      },
      {
       "expr": "process_memory_swappss_bytes{application=\"cache-movies-manager\"}",
       "legendFormat": "swappss"
      },
      {
       "expr": "process_memory_pss_bytes{application=\"cache-movies-manager\"} + process_memory_swap_bytes{application=\"cache-movies-manager\"}",
       "legendFormat": "phys (pss+swap)"
      }
     ]
    },
    {
     "title": "Cache movies cpu usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage{application=\"cache-movies-manager\"}",
       "legendFormat": "system"
      },
      {
       "expr": "process_cpu_usage{application=\"cache-movies-manager\"}",
       "legendFormat": "process"
      },
      {
       "expr": "avg_over_time(process_cpu_usage{application=\"cache-movies-manager\"}[$__rate_interval])",
       "legendFormat": "process-1h"
      }
     ]
    },
    {
     "title": "Cache movies http rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"cache-movies-manager\"}[$__rate_interval]))",
       "legendFormat": "HTTP"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache of movies business metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Movies searched",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "movies_searched_total{application=\"cache-movies-manager\"}"
      }
     ]
    },
    {
     "title": "Movies imported",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "movies_imported_total{application=\"cache-movies-manager\"}"
      }
     ]
    },
    {
     "title": "Errors during movies import",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "movies_imported_errors_total{application=\"cache-movies-manager\"}"
      }
     ]
    },
    {
     "title": "Tags added",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tags_added_total{application=\"cache-movies-manager\"}"
      }
     ]
    },
    {
     "title": "Errors during tags adding",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tags_added_errors_total{application=\"cache-movies-manager\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache of ratings + dedicated EventStore technical metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "EventStore CPU Cores",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      { "expr": "eventstore_process_cpu" }
     ]
    },
    {
     "title": "Eventstore memory",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "eventstore_process_memory_bytes"
      }
     ]
    },
    {
     "title": "Projection events per second",
     "type": "graph",
     "gridPos": { "h": 5, "w": 9, "x": 13, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(eventstore_projection_events_processed_after_restart_total[$__rate_interval])",
       "legendFormat": "{{projection}}"
      }
     ]
    },
    {
     "title": "Cache ratings JVM Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_total_used{application=\"cache-ratings-manager\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_total_committed{application=\"cache-ratings-manager\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_total_max{application=\"cache-ratings-manager\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Cache ratings threads count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_count{application=\"cache-ratings-manager\"}",
       "legendFormat": "Threads count"
      }
     ]
    },
    {
     "title": "Eventstore read / write ops/seconds",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 13, "y": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(eventstore_disk_io_read_ops[$__rate_interval])",
       "legendFormat": "read"
      },
      {
       "expr": "irate(eventstore_disk_io_write_ops[$__rate_interval])",
       "legendFormat": "write"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache of ratings business metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ratings searched",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ratings_searched_total{application=\"cache-ratings-manager\"}"
      }
     ]
    },
    {
     "title": "Ratings imported",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ratings_imported_total{application=\"cache-ratings-manager\"}"
      }
     ]
    },
    {
     "title": "Errors during ratings import",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ratings_imported_errors_total{application=\"cache-ratings-manager\"}"
      }
     ]
    },
    {
     "title": "Ratings added",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ratings_added_total{application=\"cache-ratings-manager\"}"
      }
     ]
    },
    {
     "title": "Errors during ratings adding",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ratings_added_errors_total{application=\"cache-ratings-manager\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Converter gateway technical metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Converter gateway cpu ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{service=\"converter-gateway\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Converter gateway memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 7, "y": 9 },
     "yaxes": [
      { "format": "decmbytes", "label": "MB" }
     ],
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{service=\"converter-gateway\"} / 1000000",
       "legendFormat": "virtual"
      },
      {
       "expr": "process_resident_memory_bytes{service=\"converter-gateway\"} / 1000000",
       "legendFormat": "resident"
      }
     ]
    }
   ]
  },
  {
   "title": "Converter gateway business metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tags added",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tags_added_total{application=\"converter-gateway\"}"
      }
     ]
    },
    {
     "title": "Ratings added",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ratings_added_total{application=\"converter-gateway\"}"
      }
     ]
    },
    {
     "title": "Errors during tags adding",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tags_added_errors_total{application=\"converter-gateway\"}"
      }
     ]
    },
    {
     "title": "Errors during ratings adding",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ratings_added_errors_total{application=\"converter-gateway\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nginx ingress technical metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nginx connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nginx_ingress_controller_nginx_process_connections",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Nginx cpu rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 7, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nginx_ingress_controller_nginx_process_cpu_seconds_total[$__rate_interval])",
       "legendFormat": "Cpu usage rate"
      }
     ]
    },
    {
     "title": "Nginx memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 15, "y": 11 },
     "yaxes": [
      { "format": "decmbytes", "label": "MB" }
     ],
     "targets": [
      {
       "expr": "nginx_ingress_controller_nginx_process_virtual_memory_bytes / 1000000000",
       "legendFormat": "virtual"
      },
      {
       "expr": "nginx_ingress_controller_nginx_process_resident_memory_bytes / 1000000000",
       "legendFormat": "resident"
      }
     ]
    }
   ]
  }
 ]
}