apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-deployment
  labels:
    service: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      service: rabbit
  template:
    metadata:
      labels:
        service: rabbit
    spec:
      containers:
      - name: rabbit
        image: rabbitmq:3-alpine
        ports:
        - containerPort: 5672
          name: tcp
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 512Mi
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbit-secrets
              key: rabbit-user
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbit-secrets
              key: rabbit-password
