/* 
    To avoid liveware errors
 */

export const CHANGE_SEARCH_INPUT = "CHANGE_SEARCH_INPUT";
export const CHANGE_CUSTOM_TAG_INPUT = "CHANGE_CUSTOM_TAG_INPUT";
export const CHANGE_CUSTOM_RATING = "CHANGE_CUSTOM_RATING";

export const ADD_TAG = "ADD_TAG";
export const ADD_CUSTOM_TAG_TO_CURRENT_MOVIE = "ADD_CUSTOM_TAG_TO_CURRENT_MOVIE";
export const DISPLAY_ERROR_TAGS = "DISPLAY_ERROR_TAGS";
export const DISPLAY_TAGS = "DISPLAY_TAGS";
export const FETCH_TAGS = "FETCH_TAGS";

export const DISPLAY_ERROR_MOVIES = "DISPLAY_ERROR_MOVIES";
export const DISPLAY_MOVIE = "DISPLAY_MOVIE";
export const DISPLAY_MOVIES = "DISPLAY_MOVIES";
export const FETCH_MOVIES = "FETCH_MOVIES";

export const ADD_RATING = "ADD_RATING"
export const ADD_CUSTOM_RATING_TO_CURRENT_MOVIE = "ADD_CUSTOM_RATING_TO_CURRENT_MOVIE"
export const DISPLAY_RATINGS_OF_MOVIE = "DISPLAY_RATINGS_OF_MOVIE";


