kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pv
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/k8jenkins"
