    apiVersion: v1
    kind: Service
    metadata:
      name: jenkins-service
      labels:
        service: jenkins
    spec:
      selector:
        service: jenkins
      ports:
      - port: 8080 
        name: http
      type: LoadBalancer
