apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  labels:
    service: elasticsearch
spec:
  selector:
    service: elasticsearch
  ports:
  - port: 9200
    name: main
  - port: 9300
    name: node-to-node
  clusterIP: None
