kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-pv
  namespace: internal
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk: 
    fsType: "ext4" 
    pdName: "entities-data-disk" 
