apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-deployment
  labels:
    service: sonar
spec:
  replicas: 1
  selector:
    matchLabels:
      service: sonar
  template:
    metadata:
      labels:
        service: sonar
    spec:
      containers:
      - name: sonar
        image: sonarqube:8.1-community-beta
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        env:
        - name: SONARQUBE_JDBC_USERNAME
          value: sonar
        - name: SONARQUBE_JDBC_PASSWORD
          value: sonar123
        - name: SONARQUBE_JDBC_URL
          value: jdbc:postgresql://postgres-sonar-service:5432/sonar
      initContainers:
      - name: increase-the-vm-max-map-count
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true

