    apiVersion: v1
    kind: Service
    metadata:
      name: sonar-service
      labels:
        service: sonar
    spec:
      selector:
        service: sonar
      ports:
      - port: 9000 
        name: sonarport 
      type: ClusterIP
