    apiVersion: v1
    kind: Service
    metadata:
      name: grafana-service
      namespace: monitoring
      labels:
        service: grafana
    spec:
      selector:
        service: grafana
      ports:
      - port: 3000 
        name: http
      type: NodePort
---
    apiVersion: v1
    kind: Service
    metadata:
      name: grafana-ingress-service
      labels:
        service: grafana
    spec:
      ports:
      - port: 3000
        name: http
      type: ExternalName
      externalName: grafana-service.monitoring.svc.cluster.local
