apiVersion: v1
kind: Service
metadata:
  name: keycloak-service-lb
  namespace: internal
  labels:
    service: keycloak
spec:
  ports:
  - name: https
    port: 8443
    targetPort: 8443
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: keycloak
  type: LoadBalancer
