    apiVersion: v1
    kind: Service
    metadata:
      name: keycloak-service
      namespace: internal
      labels:
        service: keycloak
    spec:
      selector:
        service: keycloak
      ports:
      - name: https
        port: 8443
      - name: http
        port: 8080
      clusterIP: None
---
    apiVersion: v1
    kind: Service
    metadata:
      name: keycloak-from-dmz-service
      labels:
        service: keycloak
    spec:
      ports:
      - name: https
        port: 8443
      - name: http
        port: 8080
      type: ExternalName
      externalName: keycloak-service.internal.svc.cluster.local

