affinity: {}

annotations: {}

extraArgs:
- --collect.collection
- --collect.database
- --collect.indexusage
- --collect.topmetrics
- --collect.connpoolstats

fullnameOverride: ""

image:
  pullPolicy: IfNotPresent
  repository: ssheehy/mongodb-exporter
  tag: 0.10.0

imagePullSecrets: []

livenessProbe:
  httpGet:
    path: /
    port: metrics
  initialDelaySeconds: 10

# [mongodb://][user:pass@]host1[:port1][,host2[:port2],...][/database][?options]
mongodb:
  uri: mongodb://mongodb_exporter:s3cr3tpassw0rd@mongo-statefulset-0.mongo-service.default.svc.cluster.local,mongo-statefulset-1.mongo-service.default.svc.cluster.local,mongo-statefulset-2.mongo-service.default.svc.cluster.local

nameOverride: ""

nodeSelector: {}

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "metrics"

port: "9216"

priorityClassName: ""

readinessProbe:
  httpGet:
    path: /
    port: metrics
  initialDelaySeconds: 10

replicas: 1

resources: {}
# limits:
#   cpu: 250m
#   memory: 192Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

# Extra environment variables that will be passed into the exporter pod
env: {}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["all"]
  readOnlyRootFilesystem: true
  runAsGroup: 10000
  runAsNonRoot: true
  runAsUser: 10000

service:
  annotations: {}
  port: 9216
  type: ClusterIP

serviceAccount:
  create: false
  # If create is true and name is not set, then a name is generated using the
  # fullname template.
  name:

serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
  namespace:
  additionalLabels: {}

tolerations: []
