apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: logging
  labels:
    service: elk-kibana
spec:
  ports:
  - port: 5601
    name: kibana
    nodePort: 30003
  selector:
    service: elk-kibana
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
  namespace: logging
  labels:
    service: elk-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      service: elk-kibana
  template:
    metadata:
      labels:
        service: elk-kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana-oss:7.9.2
        resources:
          limits:
            cpu: 2000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_HOSTS
            value: "http://elk-es-service:9200"
          - name: TELEMETRY_OPTIN
            value: "false"
        ports:
        - containerPort: 5601
