{
 "title": "Metrics from cache-ratings-manager",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of errors in log",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ch_qos_logback_core_Appender_error_events_per_second"
    }
   ]
  },
  {
   "title": "JVM Threads count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_count" }
   ]
  },
  {
   "title": "G1 GC time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_gc_G1_Old_Generation_time" },
    {
     "expr": "jvm_gc_G1_Young_Generation_time"
    }
   ]
  },
  {
   "title": "JVM Memory used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_memory_heap_used" },
    { "expr": "jvm_memory_non_heap_used" }
   ]
  }
 ]
}