{
 "title": "EventStore",
 "description": "A dashboard for metrics exported with eventstore_exporter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(eventstore_up, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "eventstore_up{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "eventstore_process_cpu{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Cluster status",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "eventstore_cluster_member_alive{instance=\"$instance\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "eventstore_cluster_member_is_leader{instance=\"$instance\"}*10000+eventstore_cluster_member_is_follower{instance=\"$instance\"}*1000+eventstore_cluster_member_is_readonly_replica{instance=\"$instance\"}*100+eventstore_cluster_member_is_clone{instance=\"$instance\"}*10+eventstore_cluster_member_is_master{instance=\"$instance\"}*1"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "eventstore_process_memory_bytes{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Projections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Projection progress",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "eventstore_projection_progress{instance=\"$instance\"}",
     "legendFormat": "{{projection}}"
    }
   ]
  },
  {
   "title": "Projection status",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "eventstore_projection_running{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Projection events per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(eventstore_projection_events_processed_after_restart_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{projection}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Read / write ops per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(eventstore_disk_io_read_ops{instance=\"$instance\"}[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "irate(eventstore_disk_io_write_ops{instance=\"$instance\"}[1m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Read / written bytes per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(eventstore_disk_io_read_bytes{instance=\"$instance\"}[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "irate(eventstore_disk_io_written_bytes{instance=\"$instance\"}[1m])",
     "legendFormat": "written"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "TCP connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "eventstore_tcp_connections{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Received / sent bytes per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(eventstore_tcp_received_bytes{instance=\"$instance\"}[1m])",
     "legendFormat": "received"
    },
    {
     "expr": "irate(eventstore_tcp_sent_bytes{instance=\"$instance\"}[1m])",
     "legendFormat": "sent"
    }
   ]
  }
 ]
}