apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    service: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
            # annotations:
            #  prometheus.io/scrape: 'true'
            #  prometheus.io/path: /actuator/prometheus
            # prometheus.io/port: '80'
      labels:
        service: webapp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: security
                operator: In
                values:
                - dmz
      containers:
      - name: webapp
        image: xbarrelet/movies-explorer-webapp
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
          - name:  webapp-config-volume
            mountPath: /usr/share/nginx/html/webapp/external-config.js
            subPath: config.js
            readOnly: true
      volumes:
        - name: webapp-config-volume
          configMap:
            name: webapp-config
