    apiVersion: v1
    kind: Service
    metadata:
      name: webapp-service
      labels:
        service: webapp
    spec:
      selector:
        service: webapp
      ports:
      - port: 80 
        name: http
      type: NodePort

