apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
data:
  mongo-user: bW92aWVzLW1hbmFnZXI=
  mongo-password: bW92aWVzLW1hbmFnZXIxMjM=
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
  namespace: internal
type: Opaque
data:
  mongo-user: bW92aWVzLW1hbmFnZXI=
  mongo-password: bW92aWVzLW1hbmFnZXIxMjM=
