    apiVersion: v1
    kind: Service
    metadata:
      name: mongo-service
      namespace: internal
      labels:
        service: mongo
    spec:
      selector:
        service: mongo
      ports:
      - port: 27017
        name: main
      clusterIP: None 

