apiVersion: v1
kind: ConfigMap
metadata:
  name: cache-ratings-manager-config
data:
  manager.ratings.host: https://movies-manager-from-dmz-service
  eventstore.host: ""
  rabbitmq.host: rabbit-service
  eventstore.cluster.nodes: "eventstore-cluster-0.eventstore-cluster.default.svc.cluster.local,eventstore-cluster-1.eventstore-cluster.default.svc.cluster.local,eventstore-cluster-2.eventstore-cluster.default.svc.cluster.local"
