    apiVersion: v1
    kind: Service
    metadata:
      name: cache-ratings-manager-service
      labels:
        service: cache-ratings-manager
    spec:
      selector:
        service: cache-ratings-manager
      ports:
      - port: 80 
        name: http
      type: NodePort
